In [1]:
## Load Lib
import pickle
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import load_model

2026-02-11 11:37:54.789711: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
/home/sheshpalsingh/anaconda3/envs/myenv/lib/python3.10/site-packages/google/api_core/_python_version_support.py:266: FutureWarning: You are using a Python version (3.10.18) which Google will stop supporting in new releases of google.api_core once it reaches its end of life (2026-10-04). Please upgrade to the latest Python version, or at least Python 3.11, to continue receiving updates for google.api_core past that date.
  warnings.warn(message, FutureWarning)

In [2]:
# Load all file
with open('01_encoded_gender.pkl','rb') as f:
    encoded_gender=pickle.load(f)
with open('02_encoded_geo.pkl','rb') as f:
    encoded_geo= pickle.load(f)
with open('03_scaler.pkl','rb') as f:
    scaler=pickle.load(f)
ANNmodel=load_model('04_model.h5')

2026-02-11 11:37:59.944542: E external/local_xla/xla/stream_executor/cuda/cuda_platform.cc:51] failed call to cuInit: INTERNAL: CUDA error: Failed call to cuInit: UNKNOWN ERROR (303)
WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

In [ ]:
input_data ={
    'CreditScore':600, 
    'Gender':'Male', 
    'Age':40, 
    'Tenure':3, 
    'Balance':60000, 
    'NumOfProducts':4,
    'HasCrCard':1, 
    'IsActiveMember':1, 
    'EstimatedSalary':5000, 
    'Geography':'France',
    
}

In [4]:
# Geo Encoded
geo_encoded=encoded_geo.transform([[input_data['Geography']]]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded,columns=encoded_geo.get_feature_names_out(['Geography']))
geo_encoded_df

/home/sheshpalsingh/anaconda3/envs/myenv/lib/python3.10/site-packages/sklearn/utils/validation.py:2749: UserWarning: X does not have valid feature names, but OneHotEncoder was fitted with feature names
  warnings.warn(

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0

In [8]:
input_df=pd.DataFrame([input_data])
input_df=pd.concat([input_df.reset_index(drop=True),geo_encoded_df],axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography,Geography_France,Geography_Germany,Geography_Spain
0,600,Male,40,3,60000,4,1,1,5000,France,1.0,0.0,0.0

In [10]:
## Gender encoding
input_df['Gender'] =encoded_gender.fit_transform(input_df['Gender'])
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,60000,4,1,1,5000,France,1.0,0.0,0.0

In [11]:
input_df=input_df.drop('Geography',axis=1)
input_df

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Geography_France,Geography_Germany,Geography_Spain
0,600,0,40,3,60000,4,1,1,5000,1.0,0.0,0.0

In [ ]:
## Scaling
scaler=scaler.transform(input_df)
scaler

array([[-0.53598516, -1.09499335,  0.10479359, -0.69539349, -0.25781119,
         4.25868381,  0.64920267,  0.97481699, -1.65923237,  1.00150113,
        -0.57946723, -0.57638802]])

In [13]:
prediction=ANNmodel.predict(input_df)
prediction

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step

array([[0.19476634]], dtype=float32)